/**
 * Left-sidebar navigation for module workspaces that do not need a custom
 * sidebar component. Each entry renders through `WorkspaceModuleSidebar`.
 */

import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Archive,
  ArrowLeftRight,
  BadgeCheck,
  Banknote,
  BarChart3,
  BellRing,
  BookOpen,
  BookText,
  Boxes,
  Cable,
  CalendarClock,
  CalendarRange,
  CircleCheck,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  Cog,
  CreditCard,
  Database,
  DoorOpen,
  Download,
  Factory,
  FileBarChart,
  FileCheck,
  FilePlus,
  FileText,
  Files,
  Folder,
  Gauge,
  Gift,
  Globe,
  Grid3x3,
  HandCoins,
  Handshake,
  Headphones,
  History,
  Hourglass,
  IdCard,
  Inbox,
  IndianRupee,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Layers,
  ListOrdered,
  ListTree,
  MailX,
  Megaphone,
  MessageSquare,
  MessageSquareWarning,
  MonitorSmartphone,
  OctagonAlert,
  Package,
  PackageMinus,
  PackagePlus,
  PackageSearch,
  Percent,
  Play,
  Plug,
  Receipt,
  RefreshCw,
  Scale,
  ScrollText,
  Server,
  ShieldCheck,
  ShoppingCart,
  Sigma,
  Siren,
  SlidersHorizontal,
  Store,
  Tags,
  Ticket,
  Timer,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Undo2,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
  Webhook,
  Wrench,
  Zap,
} from "lucide-react";

export type WorkspaceSidebarItem = {
  title: string;
  href: string;
  icon: LucideIcon;
  /** Extra path prefixes that also mark this item active (legacy or sibling routes). */
  alsoMatch?: readonly string[];
};

export type WorkspaceSidebarConfig = {
  moduleKey: string;
  root: string;
  title: string;
  subtitle: string;
  icon: LucideIcon;
  items: readonly WorkspaceSidebarItem[];
};

export const WORKSPACE_SIDEBARS: readonly WorkspaceSidebarConfig[] = [
  {
    moduleKey: "finance",
    root: "/finance",
    title: "Finance",
    subtitle: "Ledger · AR / AP · Reports",
    icon: Wallet,
    items: [
      { title: "Overview", href: "/finance", icon: LayoutDashboard },
      { title: "Chart of Accounts", href: "/finance/chart-of-accounts", icon: ListTree },
      { title: "Journals", href: "/finance/journals", icon: BookOpen },
      { title: "General Ledger", href: "/finance/gl", icon: BookText },
      {
        title: "Receivables",
        href: "/finance/ar",
        icon: HandCoins,
        alsoMatch: ["/finance/accounts-receivable"],
      },
      {
        title: "Payables",
        href: "/finance/ap",
        icon: Receipt,
        alsoMatch: ["/finance/accounts-payable"],
      },
      { title: "Periods", href: "/finance/periods", icon: CalendarRange },
      { title: "Tax Register", href: "/finance/tax-register", icon: Percent },
      { title: "Reports", href: "/finance/reports", icon: FileBarChart },
    ],
  },
  {
    moduleKey: "grc",
    root: "/grc",
    title: "GRC",
    subtitle: "Governance · Risk · Compliance",
    icon: Scale,
    items: [
      { title: "Overview", href: "/grc", icon: LayoutDashboard },
      { title: "Policies", href: "/grc/policies", icon: ScrollText },
      { title: "Risks", href: "/grc/risk-registers", icon: TriangleAlert },
      { title: "Controls", href: "/grc/controls", icon: ShieldCheck },
      {
        title: "Compliance",
        href: "/grc/compliance",
        icon: BadgeCheck,
        alsoMatch: ["/grc/compliance-"],
      },
      { title: "Audits", href: "/grc/audits", icon: ClipboardCheck },
      { title: "CAPA", href: "/grc/corrective-actions", icon: Wrench },
      { title: "Incidents", href: "/grc/incidents", icon: Siren },
    ],
  },
  {
    moduleKey: "documents",
    root: "/documents",
    title: "Documents",
    subtitle: "Document management",
    icon: FileText,
    items: [
      { title: "Overview", href: "/documents", icon: LayoutDashboard },
      { title: "Folders", href: "/documents/folders", icon: Folder },
      { title: "Documents", href: "/documents/documents", icon: Files },
      { title: "Versions", href: "/documents/document-versions", icon: History },
      { title: "Approvals", href: "/documents/document-approvals", icon: FileCheck },
      { title: "Templates", href: "/documents/templates", icon: LayoutTemplate },
      { title: "Retention", href: "/documents/retention-policies", icon: Timer },
      { title: "Archives", href: "/documents/archives", icon: Archive },
    ],
  },
  {
    moduleKey: "analytics",
    root: "/analytics",
    title: "Analytics",
    subtitle: "Dashboards · Reports · KPIs",
    icon: BarChart3,
    items: [
      { title: "Overview", href: "/analytics", icon: LayoutDashboard },
      { title: "Dashboards", href: "/analytics/dashboards", icon: LayoutGrid },
      { title: "Reports", href: "/analytics/reports", icon: FileBarChart },
      { title: "KPIs", href: "/analytics/kpis", icon: Gauge },
      { title: "Datasets", href: "/analytics/datasets", icon: Database },
      { title: "Metrics", href: "/analytics/metrics", icon: Sigma },
      { title: "Alerts", href: "/analytics/alert-rules", icon: BellRing },
      { title: "Exports", href: "/analytics/data-exports", icon: Download },
    ],
  },
  {
    moduleKey: "sales",
    root: "/sales",
    title: "Sales",
    subtitle: "Quote to invoice",
    icon: ShoppingCart,
    items: [
      { title: "Overview", href: "/sales", icon: LayoutDashboard },
      { title: "Quotes", href: "/sales/quotations", icon: FileText },
      { title: "Orders", href: "/sales/orders", icon: ShoppingCart },
      { title: "Deliveries", href: "/sales/deliveries", icon: Truck },
      { title: "Invoices", href: "/sales/invoices", icon: Receipt },
      { title: "Returns", href: "/sales/returns", icon: Undo2 },
      { title: "Pricing", href: "/sales/price-lists", icon: Tags },
      { title: "Credit", href: "/sales/customer-credit", icon: CreditCard },
    ],
  },
  {
    moduleKey: "inventory",
    root: "/inventory",
    title: "Inventory",
    subtitle: "Stock · Bins · Valuation",
    icon: Boxes,
    items: [
      { title: "Overview", href: "/inventory", icon: LayoutDashboard },
      { title: "Stock", href: "/inventory/stock", icon: Package },
      { title: "Bins", href: "/inventory/bins", icon: Grid3x3 },
      { title: "Batches", href: "/inventory/batches", icon: Layers },
      { title: "Transfers", href: "/inventory/transfers", icon: ArrowLeftRight },
      { title: "Adjustments", href: "/inventory/adjustments", icon: SlidersHorizontal },
      { title: "Valuation", href: "/inventory/valuation", icon: IndianRupee },
      { title: "Reports", href: "/inventory/reports", icon: FileBarChart },
    ],
  },
  {
    moduleKey: "manufacturing",
    root: "/manufacturing",
    title: "Manufacturing",
    subtitle: "BOM · Production · WIP",
    icon: Factory,
    items: [
      { title: "Overview", href: "/manufacturing", icon: LayoutDashboard },
      { title: "BOMs", href: "/manufacturing/boms", icon: ListTree },
      { title: "Orders", href: "/manufacturing/production-orders", icon: ClipboardList },
      { title: "Issues", href: "/manufacturing/material-issues", icon: PackageMinus },
      { title: "Receipts", href: "/manufacturing/production-receipts", icon: PackagePlus },
      { title: "WIP", href: "/manufacturing/wip", icon: Hourglass },
      { title: "Scrap", href: "/manufacturing/scrap", icon: Trash2 },
      { title: "Machines", href: "/manufacturing/machines", icon: Cog },
    ],
  },
  {
    moduleKey: "quality",
    root: "/quality",
    title: "Quality",
    subtitle: "Inspections · NCR · CAPA",
    icon: ClipboardCheck,
    items: [
      { title: "Overview", href: "/quality", icon: LayoutDashboard },
      { title: "Incoming", href: "/quality/incoming-inspections", icon: PackageSearch },
      { title: "In-Process", href: "/quality/inprocess-inspections", icon: Activity },
      { title: "Final", href: "/quality/final-inspections", icon: BadgeCheck },
      { title: "NCRs", href: "/quality/ncrs", icon: OctagonAlert },
      { title: "CAPAs", href: "/quality/capas", icon: Wrench },
      { title: "Audits", href: "/quality/audits", icon: ClipboardCheck },
      { title: "Complaints", href: "/quality/complaints", icon: MessageSquareWarning },
    ],
  },
  {
    moduleKey: "payroll",
    root: "/payroll",
    title: "Payroll",
    subtitle: "Runs · Payslips · Loans",
    icon: Banknote,
    items: [
      { title: "Overview", href: "/payroll", icon: LayoutDashboard },
      { title: "Periods", href: "/payroll/payroll-periods", icon: CalendarRange },
      { title: "Salaries", href: "/payroll/employee-salaries", icon: Banknote },
      { title: "Runs", href: "/payroll/payroll-runs", icon: Play },
      { title: "Payslips", href: "/payroll/payslips", icon: Receipt },
      { title: "Bonuses", href: "/payroll/bonuses", icon: Gift },
      { title: "Loans", href: "/payroll/loans", icon: HandCoins },
      { title: "Summaries", href: "/payroll/payroll-summaries", icon: FileBarChart },
    ],
  },
  {
    moduleKey: "recruitment",
    root: "/recruitment",
    title: "Recruitment",
    subtitle: "Requisition to onboarding",
    icon: UserPlus,
    items: [
      { title: "Overview", href: "/recruitment", icon: LayoutDashboard },
      { title: "Requisitions", href: "/recruitment/job-requisitions", icon: FilePlus },
      { title: "Postings", href: "/recruitment/job-postings", icon: Megaphone },
      { title: "Candidates", href: "/recruitment/candidates", icon: Users },
      { title: "Applications", href: "/recruitment/applications", icon: FileText },
      { title: "Interviews", href: "/recruitment/interviews", icon: CalendarClock },
      { title: "Offers", href: "/recruitment/offers", icon: Handshake },
      { title: "Onboarding", href: "/recruitment/onboarding", icon: DoorOpen },
    ],
  },
  {
    moduleKey: "helpdesk",
    root: "/helpdesk",
    title: "Helpdesk",
    subtitle: "Tickets · SLAs · Knowledge",
    icon: Headphones,
    items: [
      { title: "Overview", href: "/helpdesk", icon: LayoutDashboard },
      { title: "Tickets", href: "/helpdesk/tickets", icon: Ticket },
      { title: "Assignments", href: "/helpdesk/ticket-assignments", icon: UserCheck },
      { title: "Escalations", href: "/helpdesk/ticket-escalations", icon: TrendingUp },
      { title: "Knowledge", href: "/helpdesk/knowledge-articles", icon: BookOpen },
      { title: "Resolutions", href: "/helpdesk/resolutions", icon: CircleCheck },
      { title: "Teams", href: "/helpdesk/support-teams", icon: Users },
      { title: "Feedback", href: "/helpdesk/customer-feedback", icon: MessageSquare },
    ],
  },
  {
    moduleKey: "integration",
    root: "/integration",
    title: "Integration",
    subtitle: "Systems · Webhooks · Sync",
    icon: Plug,
    items: [
      { title: "Overview", href: "/integration", icon: LayoutDashboard },
      { title: "Systems", href: "/integration/external-systems", icon: Server },
      { title: "Connectors", href: "/integration/connectors", icon: Cable },
      { title: "Webhooks", href: "/integration/webhooks", icon: Webhook },
      { title: "Events", href: "/integration/event-definitions", icon: Zap },
      { title: "Queues", href: "/integration/message-queues", icon: ListOrdered },
      { title: "Sync", href: "/integration/sync-jobs", icon: RefreshCw },
      { title: "Dead Letters", href: "/integration/dead-letters", icon: MailX },
    ],
  },
  {
    moduleKey: "ecommerce",
    root: "/ecommerce",
    title: "Ecommerce",
    subtitle: "Stores · Orders · Returns",
    icon: Store,
    items: [
      { title: "Overview", href: "/ecommerce", icon: LayoutDashboard },
      { title: "Stores", href: "/ecommerce/stores", icon: Store },
      { title: "Listings", href: "/ecommerce/product-listings", icon: Tags },
      { title: "Carts", href: "/ecommerce/customer-carts", icon: ShoppingCart },
      { title: "Orders", href: "/ecommerce/orders", icon: ClipboardList },
      { title: "Payments", href: "/ecommerce/payments", icon: CreditCard },
      { title: "Shipments", href: "/ecommerce/shipments", icon: Truck },
      { title: "Returns", href: "/ecommerce/return-requests", icon: Undo2 },
    ],
  },
  {
    moduleKey: "portal",
    root: "/portal",
    title: "Portal",
    subtitle: "Customer self-service",
    icon: Globe,
    items: [
      { title: "Overview", href: "/portal", icon: LayoutDashboard },
      { title: "Accounts", href: "/portal/portal-accounts", icon: CircleUser },
      { title: "Profiles", href: "/portal/customer-profiles", icon: IdCard },
      { title: "Sessions", href: "/portal/portal-sessions", icon: MonitorSmartphone },
      { title: "Orders", href: "/portal/order-views", icon: ClipboardList },
      { title: "Invoices", href: "/portal/invoice-views", icon: Receipt },
      { title: "Tickets", href: "/portal/support-tickets", icon: Ticket },
      { title: "Requests", href: "/portal/service-requests", icon: Inbox },
    ],
  },
];

export function isWorkspaceItemActive(
  pathname: string,
  root: string,
  item: Pick<WorkspaceSidebarItem, "href" | "alsoMatch">,
): boolean {
  if (item.href === root) return pathname === root;
  if (pathname === item.href || pathname.startsWith(`${item.href}/`)) return true;
  return (item.alsoMatch ?? []).some((prefix) => pathname.startsWith(prefix));
}
